// Package chunk は検索対象の最小単位を表す。
//
// フィールド名は NeNe Corpus の Chunk エンティティに一対一で写せるよう揃えている
// (nene-corpus/src/Chunk/Chunk.php)。Phase 2 の統合時に変換層を薄く保つため。
package chunk

import "github.com/hideyukiMORI/nene-recall/internal/org"

// Chunk は文書を分割した一片。
type Chunk struct {
	ID    int64  `json:"chunk_id"`
	OrgID org.ID `json:"-"` // 応答には出さない。分離はサーバ側の責務 (ADR 0003)
	// ExternalID は外部システム（Corpus）が持つ id である。nil は「外部の id を
	// 持たない」を意味する (docs/adr/0020-phase2-corpus-integration-contract.md)。
	//
	// 🔴 ID と混ぜないこと。ID は Recall の採番（identity 列）で、ExternalID は
	// 呼び出し側の識別子である。1つの列に両方を入れると、明示 id が
	// GENERATED BY DEFAULT AS IDENTITY のシーケンスを進めないまま値を消費し、
	// 後続の採番が既存行と衝突する。ADR 0020 Decision 1 が却下した選択肢そのもの。
	//
	// 🔴 ポインタなのは「0 が来た」と「指定が無かった」を区別するためである。
	// 値型にすると未指定が 0 になり、0 という外部 id と見分けがつかない。
	ExternalID   *int64  `json:"external_id"`
	DocumentID   int64   `json:"document_id"`
	SourceID     int64   `json:"source_id"`
	ChunkIndex   int     `json:"chunk_index"`
	Content      string  `json:"content"`
	PageNumber   *int    `json:"page_number"`
	SectionLabel *string `json:"section_label"`
}
