package httpapi

import (
	"log/slog"
	"net/http"
	"strconv"

	"github.com/hideyukiMORI/nene-recall/internal/chunk"
	"github.com/hideyukiMORI/nene-recall/internal/org"
)

// chunkInput は投入される1件。docs/openapi/openapi.yaml の ChunkInput と対応する。
//
// ChunkID をポインタで受けるのは、指定されたことを検知して拒否するためである。
// 値型にすると 0（未指定）と 0 を明示した場合が区別できない。
// ExternalID も同じ理由でポインタだが、こちらは受け入れる値である。
type chunkInput struct {
	ChunkID *int64 `json:"chunk_id"`
	// ExternalID は Corpus 側の chunks.id
	// (docs/adr/0020-phase2-corpus-integration-contract.md Decision 1)。
	// 省略・null は「外部 id を持たない」。
	ExternalID   *int64  `json:"external_id"`
	DocumentID   int64   `json:"document_id"`
	SourceID     int64   `json:"source_id"`
	ChunkIndex   int     `json:"chunk_index"`
	Content      string  `json:"content"`
	PageNumber   *int    `json:"page_number"`
	SectionLabel *string `json:"section_label"`
}

// putChunksRequest は POST /v1/chunks の入力。
type putChunksRequest struct {
	OrgID  *int64       `json:"org_id"`
	Chunks []chunkInput `json:"chunks"`
}

// putChunksResponse は POST /v1/chunks の応答。
//
// 🔑 ExternalIDs は要求の external_id を ChunkIDs と同じ順で返したものである。
// 呼び出し側（Corpus）は自分の id と Recall の採番の対応を、要求と応答を
// 突き合わせずに1つの応答から作れる。置き換えが起きた場合、chunk_ids に
// 入るのは新しい採番ではなく既存行の id である (ADR 0020 Decision 1)。
type putChunksResponse struct {
	Accepted    int      `json:"accepted"`
	ChunkIDs    []int64  `json:"chunk_ids"`
	ExternalIDs []*int64 `json:"external_ids"`
}

// deleteCountResponse は一括削除の応答。source 単位と document 単位で共通。
//
// 🔴 2つの応答を別の型に分けない。片方だけ形が変わると、呼び出し側は
// 「削除の応答」を1つの形として扱えなくなる。
type deleteCountResponse struct {
	Deleted int `json:"deleted"`
}

// toChunks は要求を検証して chunk.Chunk の列に変換する。
func (req putChunksRequest) toChunks() (org.ID, []chunk.Chunk, error) {
	orgID, err := requireBodyOrgID(req.OrgID)
	if err != nil {
		return 0, nil, err
	}

	if len(req.Chunks) == 0 {
		return 0, nil, invalid("chunks_required", "chunks must contain at least one item")
	}

	out := make([]chunk.Chunk, 0, len(req.Chunks))

	for i, in := range req.Chunks {
		if err := in.validate(i); err != nil {
			return 0, nil, err
		}

		out = append(out, chunk.Chunk{
			ID:           0,
			OrgID:        orgID,
			ExternalID:   in.ExternalID,
			DocumentID:   in.DocumentID,
			SourceID:     in.SourceID,
			ChunkIndex:   in.ChunkIndex,
			Content:      in.Content,
			PageNumber:   in.PageNumber,
			SectionLabel: in.SectionLabel,
		})
	}

	return orgID, out, nil
}

// validate は1件ぶんの入力を検証する。i は応答に出す添字。
func (in chunkInput) validate(i int) error {
	// 🔴 明示 chunk_id は受け付けない。id 列は GENERATED BY DEFAULT AS IDENTITY
	// なので書けてしまうが、書いてもシーケンスは進まず、後続の採番が既存行と
	// 衝突する。外部の識別子は external_id で受ける
	// (docs/adr/0020-phase2-corpus-integration-contract.md Decision 1)。
	if in.ChunkID != nil {
		return invalid("chunk_id_not_accepted",
			"chunk_id must not be set; use external_id for the caller's own id "+
				"(Recall assigns chunk_id itself)")
	}

	// 🔴 0 と負値を弾く。「外部 id を持たない」は null（キーの省略）で表す。
	// 0 を通すと、置き換えの鍵が実在しない 0 番になる。
	if in.ExternalID != nil && *in.ExternalID < 1 {
		return invalid("external_id_invalid",
			"chunks["+strconv.Itoa(i)+"].external_id must be a positive integer")
	}

	if in.Content == "" {
		return invalid("content_required",
			"chunks["+strconv.Itoa(i)+"].content must not be empty")
	}

	return nil
}

// externalIDsOf は入力の external_id を入力と同じ順で並べる。
//
// 🔴 応答の chunk_ids と同じ順であることが契約なので、Writer に渡した
// チャンク列から作る。要求の別の場所から作り直すと、順序が一致している保証を
// 失う（Put の戻り値は「入力と同じ順」・ADR 0013）。
func externalIDsOf(chunks []chunk.Chunk) []*int64 {
	ids := make([]*int64, 0, len(chunks))
	for _, c := range chunks {
		ids = append(ids, c.ExternalID)
	}

	return ids
}

// handlePutChunks はチャンクを投入する。
func (s *Server) handlePutChunks(w http.ResponseWriter, r *http.Request) {
	var req putChunksRequest
	if !s.decodeJSON(w, r, &req) {
		return
	}

	orgID, chunks, err := req.toChunks()
	if err != nil {
		s.writeRequestError(w, err)

		return
	}

	ids, err := s.deps.Writer.Put(r.Context(), orgID, chunks)
	if err != nil {
		s.writeDependencyError(w, "put_chunks", err)

		return
	}

	s.log.Info("chunks accepted",
		slog.String("org_id", orgID.String()),
		slog.Int("count", len(ids)),
	)

	s.writeJSON(w, http.StatusOK, putChunksResponse{
		Accepted:    len(ids),
		ChunkIDs:    ids,
		ExternalIDs: externalIDsOf(chunks),
	})
}

// pathInt64 はパス変数を int64 として取り出す。
func (s *Server) pathInt64(w http.ResponseWriter, r *http.Request, name, code string) (int64, bool) {
	raw := r.PathValue(name)

	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		s.writeError(w, http.StatusBadRequest, code, name+" must be an integer")

		return 0, false
	}

	return value, true
}

// handleDeleteChunk は1件を削除する。
//
// 対象が無くても 204 を返す。削除の意味は「その状態にすること」であり、
// 既にその状態なら要求は満たされている。
func (s *Server) handleDeleteChunk(w http.ResponseWriter, r *http.Request) {
	orgID, ok := s.requireOrgID(w, r)
	if !ok {
		return
	}

	chunkID, ok := s.pathInt64(w, r, "chunk_id", "invalid_chunk_id")
	if !ok {
		return
	}

	if err := s.deps.Writer.Delete(r.Context(), orgID, chunkID); err != nil {
		s.writeDependencyError(w, "delete_chunk", err)

		return
	}

	w.WriteHeader(http.StatusNoContent)
}

// handleDeleteBySource は source 単位で一括削除し、件数を返す。
func (s *Server) handleDeleteBySource(w http.ResponseWriter, r *http.Request) {
	orgID, ok := s.requireOrgID(w, r)
	if !ok {
		return
	}

	sourceID, ok := s.pathInt64(w, r, "source_id", "invalid_source_id")
	if !ok {
		return
	}

	deleted, err := s.deps.Writer.DeleteBySource(r.Context(), orgID, sourceID)
	if err != nil {
		s.writeDependencyError(w, "delete_by_source", err)

		return
	}

	s.log.Info("chunks deleted by source",
		slog.String("org_id", orgID.String()),
		slog.Int("deleted", deleted),
	)

	s.writeJSON(w, http.StatusOK, deleteCountResponse{Deleted: deleted})
}

// handleDeleteByDocument は document 単位で一括削除し、件数を返す。
//
// 🔴 org_id の受け方も応答の形も source 版と揃える。Corpus の削除経路が
// document 単位と source 単位の2つあるので (ADR 0020 Decision 2)、
// 呼び出し側は2つを同じ形で扱えなければならない。
func (s *Server) handleDeleteByDocument(w http.ResponseWriter, r *http.Request) {
	orgID, ok := s.requireOrgID(w, r)
	if !ok {
		return
	}

	documentID, ok := s.pathInt64(w, r, "document_id", "invalid_document_id")
	if !ok {
		return
	}

	deleted, err := s.deps.Writer.DeleteByDocument(r.Context(), orgID, documentID)
	if err != nil {
		s.writeDependencyError(w, "delete_by_document", err)

		return
	}

	s.log.Info("chunks deleted by document",
		slog.String("org_id", orgID.String()),
		slog.Int("deleted", deleted),
	)

	s.writeJSON(w, http.StatusOK, deleteCountResponse{Deleted: deleted})
}
