package httpapi

import (
	"log/slog"
	"net/http"
	"strconv"

	"github.com/hideyukiMORI/nene-recall/internal/chunk"
	"github.com/hideyukiMORI/nene-recall/internal/org"
)

// chunkInput は投入される1件。docs/openapi/openapi.yaml の ChunkInput と対応する。
//
// ChunkID をポインタで受けるのは、指定されたことを検知して拒否するためである。
// 値型にすると 0（未指定）と 0 を明示した場合が区別できない。
type chunkInput struct {
	ChunkID      *int64  `json:"chunk_id"`
	DocumentID   int64   `json:"document_id"`
	SourceID     int64   `json:"source_id"`
	ChunkIndex   int     `json:"chunk_index"`
	Content      string  `json:"content"`
	PageNumber   *int    `json:"page_number"`
	SectionLabel *string `json:"section_label"`
}

// putChunksRequest は POST /v1/chunks の入力。
type putChunksRequest struct {
	OrgID  *int64       `json:"org_id"`
	Chunks []chunkInput `json:"chunks"`
}

// putChunksResponse は POST /v1/chunks の応答。
type putChunksResponse struct {
	Accepted int     `json:"accepted"`
	ChunkIDs []int64 `json:"chunk_ids"`
}

// deleteBySourceResponse は source 単位の削除の応答。
type deleteBySourceResponse struct {
	Deleted int `json:"deleted"`
}

// toChunks は要求を検証して chunk.Chunk の列に変換する。
func (req putChunksRequest) toChunks() (org.ID, []chunk.Chunk, error) {
	orgID, err := requireBodyOrgID(req.OrgID)
	if err != nil {
		return 0, nil, err
	}

	if len(req.Chunks) == 0 {
		return 0, nil, invalid("chunks_required", "chunks must contain at least one item")
	}

	out := make([]chunk.Chunk, 0, len(req.Chunks))

	for i, in := range req.Chunks {
		// 🔴 明示 chunk_id は受け付けない（施主決定・Phase 1）。id 列は
		// GENERATED BY DEFAULT AS IDENTITY なので書けてしまうが、書いても
		// シーケンスは進まず、後続の採番が既存行と衝突する。
		// 受け入れ方式は Phase 2 の ADR で決める。
		if in.ChunkID != nil {
			return 0, nil, invalid("chunk_id_not_accepted",
				"chunk_id must not be set; Recall assigns ids in phase 1")
		}

		if in.Content == "" {
			return 0, nil, invalid("content_required",
				"chunks["+strconv.Itoa(i)+"].content must not be empty")
		}

		out = append(out, chunk.Chunk{
			ID:           0,
			OrgID:        orgID,
			DocumentID:   in.DocumentID,
			SourceID:     in.SourceID,
			ChunkIndex:   in.ChunkIndex,
			Content:      in.Content,
			PageNumber:   in.PageNumber,
			SectionLabel: in.SectionLabel,
		})
	}

	return orgID, out, nil
}

// handlePutChunks はチャンクを投入する。
func (s *Server) handlePutChunks(w http.ResponseWriter, r *http.Request) {
	var req putChunksRequest
	if !s.decodeJSON(w, r, &req) {
		return
	}

	orgID, chunks, err := req.toChunks()
	if err != nil {
		s.writeRequestError(w, err)

		return
	}

	ids, err := s.deps.Writer.Put(r.Context(), orgID, chunks)
	if err != nil {
		s.writeDependencyError(w, "put_chunks", err)

		return
	}

	s.log.Info("chunks accepted",
		slog.String("org_id", orgID.String()),
		slog.Int("count", len(ids)),
	)

	s.writeJSON(w, http.StatusOK, putChunksResponse{Accepted: len(ids), ChunkIDs: ids})
}

// pathInt64 はパス変数を int64 として取り出す。
func (s *Server) pathInt64(w http.ResponseWriter, r *http.Request, name, code string) (int64, bool) {
	raw := r.PathValue(name)

	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		s.writeError(w, http.StatusBadRequest, code, name+" must be an integer")

		return 0, false
	}

	return value, true
}

// handleDeleteChunk は1件を削除する。
//
// 対象が無くても 204 を返す。削除の意味は「その状態にすること」であり、
// 既にその状態なら要求は満たされている。
func (s *Server) handleDeleteChunk(w http.ResponseWriter, r *http.Request) {
	orgID, ok := s.requireOrgID(w, r)
	if !ok {
		return
	}

	chunkID, ok := s.pathInt64(w, r, "chunk_id", "invalid_chunk_id")
	if !ok {
		return
	}

	if err := s.deps.Writer.Delete(r.Context(), orgID, chunkID); err != nil {
		s.writeDependencyError(w, "delete_chunk", err)

		return
	}

	w.WriteHeader(http.StatusNoContent)
}

// handleDeleteBySource は source 単位で一括削除し、件数を返す。
func (s *Server) handleDeleteBySource(w http.ResponseWriter, r *http.Request) {
	orgID, ok := s.requireOrgID(w, r)
	if !ok {
		return
	}

	sourceID, ok := s.pathInt64(w, r, "source_id", "invalid_source_id")
	if !ok {
		return
	}

	deleted, err := s.deps.Writer.DeleteBySource(r.Context(), orgID, sourceID)
	if err != nil {
		s.writeDependencyError(w, "delete_by_source", err)

		return
	}

	s.log.Info("chunks deleted by source",
		slog.String("org_id", orgID.String()),
		slog.Int("deleted", deleted),
	)

	s.writeJSON(w, http.StatusOK, deleteBySourceResponse{Deleted: deleted})
}
