-- 0001: chunks テーブルと pgvector 拡張。
--
-- 🔴 マイグレーションは forward-only である。down を書かない。
--    詳細と理由は migrate.go の冒頭コメントを参照。

CREATE EXTENSION IF NOT EXISTS vector;

-- chunks は検索対象の最小単位を1行1チャンクで持つ。
--
-- 🔴 UNIQUE 制約を張らない（2026-09-01 施主決定）。
--    (org_id, document_id, chunk_index) は一見「同一チャンク」を表す自然キーに
--    見えるが、Corpus の実データでそれが本当に一意なのかをまだ確かめていない。
--    ここで UNIQUE を張ると「どの列で同一とみなすか」を今この場で決めたことに
--    なり、後から緩めるのは（既に入ったデータごと）高くつく。
--    再投入は insert-only とし、upsert もしない。再取り込みは
--    DeleteBySource → Put の2手順を呼び出し側の規約とする。
--    同一性の判断は Phase 2（Corpus の実データが見えるとき）まで遅延させる。
--
-- 🔴 id は GENERATED BY DEFAULT AS IDENTITY だが、Phase 1 では明示 id を
--    受け入れない（writer.go が chunk.Chunk.ID != 0 を拒否する）。
--    明示 id と IDENTITY の混在はシーケンスを進めないまま値を消費するため、
--    後続の採番と衝突する。Corpus 由来の chunk_id をどう受け入れるかは
--    Phase 2 の ADR で決める。列と型は既に対応しているので後戻りは無い。
CREATE TABLE chunks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT  NOT NULL CHECK (org_id >= 1),
    document_id   BIGINT  NOT NULL,
    source_id     BIGINT  NOT NULL,
    chunk_index   INTEGER NOT NULL CHECK (chunk_index >= 0),
    content       TEXT    NOT NULL CHECK (content <> ''),
    page_number   INTEGER,
    section_label TEXT,

    -- embedder_id を単一行のメタテーブルではなく行ごとの列に持つ。
    --
    -- メタテーブルにすると、全行を削除してからモデルを切り替えたときに
    -- 古いメタだけが残り、空のストアが新規の取り込みを誤って拒否する。
    -- 行ごとに持てば「行が無ければ矛盾も無い」となり、その状態は自己治癒する。
    -- 不一致の検知は「自分と違う embedder_id の行が1件でもあるか」で行う。
    embedder_id   TEXT    NOT NULL CHECK (embedder_id <> ''),

    -- 次元は vector(1024)。internal/store/postgres の vectorDimensions と対になる。
    -- 次元の異なるプロバイダへ移るにはこの列の変更＝マイグレーションが要るので、
    -- Go 側は実行時の設定値ではなく定数として持ち、接続時に突き合わせる。
    embedding     vector(1024) NOT NULL,

    -- API には出さない。取り込み時期の追跡と、将来の再取り込み判断のために持つ。
    -- 既定値を DB 側に置くので Go は時刻を読まない（ARC-002 に無関係でいられる）。
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 分離条件（org_id）と絞り込み条件を先頭に置いた B-tree 索引。
-- org_id 単独の索引を別に作らないのは、この複合索引の先頭列で足りるため。
CREATE INDEX chunks_org_document_idx ON chunks (org_id, document_id);
CREATE INDEX chunks_org_source_idx   ON chunks (org_id, source_id);

-- embedder_id 不一致の検知（自分と違う値の行を1件探す）に使う。
CREATE INDEX chunks_embedder_idx ON chunks (embedder_id);

-- 🔴🔴 embedding 列にベクトル索引（HNSW / IVFFlat）を作らないこと。
--
-- ⚠️ この禁止は 0004_add_search_indexes.sql で**解けている**（2026-09-02）。
--    下の手順 2（10万件で測る）が docs/benchmarks/2026-09-02-eval-100k-before-index.md
--    で終わり、手順 3 として HNSW を張った。以下は当時の記録として残す。
--
-- ADR 0007 の成果物は「pgvector を選んだこと」ではなく
-- 「測ってから索引を入れた経路」である。最初から索引を張ると before の数字が
-- 取れず、なぜ索引を入れたのかを数字で語れなくなる。ADR 0007 が定めた手順は
-- 固定されている:
--   1. 索引なしで Phase 1 を完成させる
--   2. 10万件規模で p95 と recall を測り docs/benchmarks/ に残す
--   3. CREATE INDEX ... USING hnsw を入れ、before/after を並べて記録する
-- 上の B-tree 索引はこの禁止の対象ではない（禁じているのはベクトル索引）。
