-- 0003: 外部システム（Corpus）の id を受けるための列。
--
-- 🔴 マイグレーションは forward-only である。down を書かない。
--    詳細と理由は migrate.go の冒頭コメントを参照。
--
-- 判断の正本は docs/adr/0020-phase2-corpus-integration-contract.md の Decision 1。

-- external_id は Corpus 側の chunks.id である。
--
-- 🔴 id 列に Corpus の id を書かせる案は却下してある（ADR 0020 の却下表）。
--    id は GENERATED BY DEFAULT AS IDENTITY なので明示 id も書けるが、書いても
--    シーケンスは進まず、後続の採番が既存行と衝突する。「外部の識別子」と
--    「自分の採番」を1つの列に混ぜない、というのがこの列が存在する理由である。
--
-- NULL を許すのは、単体運用（recallctl・評価ハーネス）では外部の id が
-- そもそも存在しないためである。「外部 id を持たない」を表す値は NULL しかない。
ALTER TABLE chunks
    ADD COLUMN external_id BIGINT;

-- 同じ (org_id, external_id) の再投入を「置き換え」にするための一意制約。
--
-- 🔑 org_id を先頭に含めるのは、外部 id が org を跨いで一意である保証がどこにも
--    無いためである。external_id 単独に一意制約を張ると、別テナントの取り込みが
--    互いを弾き合う。分離条件は制約にも現れていなければならない (ADR 0003)。
--
-- 🔑 部分一意（WHERE external_id IS NOT NULL）にしていない。PostgreSQL の
--    UNIQUE は NULL どうしを重複とみなさないので、external_id を持たない行は
--    何行でも入る。実測で確認済みであり、部分索引にしても振る舞いは変わらない。
--
-- 🔴 この制約は Writer の ON CONFLICT (org_id, external_id) の対象そのものである。
--    消すと upsert が「制約が無い」で実行時に落ちる。
ALTER TABLE chunks
    ADD CONSTRAINT chunks_org_external_id_key UNIQUE (org_id, external_id);
