package postgres

import (
	"errors"
	"fmt"
)

// ---------------------------------------------------------------------------
// ベクトルの契約違反
// ---------------------------------------------------------------------------

// errVectorInvalid は、ベクトルが embed.Embedder の契約を満たしていないことを表す。
//
// 呼び出し側が「ベクトルが理由で書けなかった」を一度に判定できるよう、
// 個別の理由（次元・正規化）はこれを包む。errors.Is はこの入れ子を辿る。
var errVectorInvalid = errors.New("postgres: vector does not satisfy the Embedder contract")

// errVectorDimensions は、ベクトルの次元数が vector(1024) 列と一致しないことを表す。
//
// 🔴 これは設定ミスであってデータの問題ではない。次元が違うベクトルは
// そもそも列に入らないので、取り込みを止めて設定を直させること。
var errVectorDimensions = fmt.Errorf("%w: unexpected dimensions", errVectorInvalid)

// errVectorNotNormalized は、ベクトルが L2 正規化されていないことを表す。
//
// 🔴 検索側の <#>（負の内積）は入力が正規化済みであることに依存している。
// これを見逃すと、エラーにならないまま順位だけが静かに狂う
// (docs/adr/0005-embedding-provider-is-pluggable.md)。
// 沈黙させないために、書き込みの時点で失敗にする。
var errVectorNotNormalized = fmt.Errorf("%w: vector is not L2-normalized", errVectorInvalid)

// ---------------------------------------------------------------------------
// 接続と構築
// ---------------------------------------------------------------------------

// errConnect は接続そのものが確立できないことを表す。
var errConnect = errors.New("postgres: cannot reach the database")

// errEmbedderDimensions は Embedder の次元数が vector(1024) 列と噛み合わないことを表す。
//
// 🔴 これを New で弾かないと「起動はするが取り込みが全部落ちる」構成が作れてしまう。
// config.EmbedDimensions は実行時に変えられるが、列の次元は DDL で固定されている。
var errEmbedderDimensions = errors.New("postgres: embedder dimensions do not match the column")

// errEmbedderID は Embedder が空の識別子を返したことを表す。
//
// embedder_id 列は空文字を拒否する CHECK を持つので、空のまま進むと
// 取り込みの瞬間に制約違反という分かりにくい形で落ちる。構築時に潰す。
var errEmbedderID = errors.New("postgres: embedder returned an empty identifier")

// ---------------------------------------------------------------------------
// マイグレーション
// ---------------------------------------------------------------------------

// errMigrate はスキーマの適用に失敗したことを表す。
var errMigrate = errors.New("postgres: migration failed")

// ---------------------------------------------------------------------------
// 書き込み
// ---------------------------------------------------------------------------

// errWrite は書き込み経路の SQL が失敗したことを表す。
var errWrite = errors.New("postgres: write failed")

// errEmptyBatch は Put に空のチャンク列が渡されたことを表す。
//
// 空を「成功・0件」で返すと (nil, nil) になり GO-004 に反する。
// 呼び出し側の組み立てミスを黙って飲み込まないよう、明示的に拒否する。
var errEmptyBatch = errors.New("postgres: no chunks to write")

// errEmptyContent は Content が空のチャンクが混じっていたことを表す。
//
// 空文字は埋め込みに意味を持たず、content 列の CHECK にも掛かる。
// 埋め込みを生成する前に弾いて、無駄な外部 I/O を避ける。
var errEmptyContent = errors.New("postgres: chunk content is empty")

// errOrgRequired は org の識別子が未指定（ゼロ値）のまま届いたことを表す。
//
// 🔴 DB の CHECK (org_id >= 1) に守らせない。制約に落とすと失敗が「制約違反」に
// なり、呼び出し側は原因に辿り着けない。ゼロ値がここまで届いたということは
// 上流にバグがあるということで、それを分かりにくい失敗で覆い隠さない。
// 「org_id が無いとき」を表す ID は存在せず、未指定は error である (ADR 0003)。
var errOrgRequired = errors.New("postgres: org id is required")

// errOrgMismatch は Chunk.OrgID が引数の orgID と食い違うことを表す。
//
// 🔴 引数の orgID を唯一の正とし、食い違いを黙って上書きしない。
// 上書きすると、呼び出し側の取り違えが「別テナントへの書き込み」として成功する
// (docs/adr/0003-org-id-is-mandatory.md)。
var errOrgMismatch = errors.New("postgres: chunk org_id does not match the requested org")

// errChunkIDNotAccepted は明示的な chunk_id が渡されたことを表す。
//
// 🔴 id 列は GENERATED BY DEFAULT AS IDENTITY なので明示 id も書けてしまうが、
// 書いてもシーケンスは進まず、後続の採番が既存行と衝突する。
// Corpus 由来の chunk_id の受け入れ方式は Phase 2 の ADR で決める（施主決定）。
var errChunkIDNotAccepted = errors.New("postgres: explicit chunk id is not accepted in phase 1")

// ---------------------------------------------------------------------------
// 検索
// ---------------------------------------------------------------------------

// errSearch は検索経路の SQL が失敗したことを表す。
var errSearch = errors.New("postgres: search failed")
